// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUhnc-GrfxqU4YKRFPYoNOUWNNMnZSQq0',
    appId: '1:601811842843:web:a6f2d757facb479d2105be',
    messagingSenderId: '601811842843',
    projectId: 'clarity-339fa',
    authDomain: 'clarity-339fa.firebaseapp.com',
    storageBucket: 'clarity-339fa.firebasestorage.app',
    measurementId: 'G-4N6GESE9D1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHymL6cub5bBMVYhCxHcpA4V1nZ3QdNB4',
    appId: '1:601811842843:android:201e2560f0e735ad2105be',
    messagingSenderId: '601811842843',
    projectId: 'clarity-339fa',
    storageBucket: 'clarity-339fa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGN7D17lLpvzg3FcKt2BpzQ8nXR8F8Tmg',
    appId: '1:601811842843:ios:bda4e3047180a57d2105be',
    messagingSenderId: '601811842843',
    projectId: 'clarity-339fa',
    storageBucket: 'clarity-339fa.firebasestorage.app',
    iosClientId: '601811842843-5a2vdqah5n8mer6f6m2eq2v3stiogj28.apps.googleusercontent.com',
    iosBundleId: 'com.example.clarity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGN7D17lLpvzg3FcKt2BpzQ8nXR8F8Tmg',
    appId: '1:601811842843:ios:bda4e3047180a57d2105be',
    messagingSenderId: '601811842843',
    projectId: 'clarity-339fa',
    storageBucket: 'clarity-339fa.firebasestorage.app',
    iosClientId: '601811842843-5a2vdqah5n8mer6f6m2eq2v3stiogj28.apps.googleusercontent.com',
    iosBundleId: 'com.example.clarity',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUhnc-GrfxqU4YKRFPYoNOUWNNMnZSQq0',
    appId: '1:601811842843:web:a538dbf5ee7c56522105be',
    messagingSenderId: '601811842843',
    projectId: 'clarity-339fa',
    authDomain: 'clarity-339fa.firebaseapp.com',
    storageBucket: 'clarity-339fa.firebasestorage.app',
    measurementId: 'G-CJCQM1V9R8',
  );

}